# @package eval.knowundo.metrics.retain_ROUGE
defaults:
  - ../../data/datasets@datasets: KnowUnDo_retain_eval
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default

handler: rouge
rouge_type: rougeL_recall
batch_size: ${eval.knowundo.batch_size}

datasets:
  KnowUnDo_retain_eval:
    args:
      hf_args:
        name: ${eval.knowundo.domain}
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset:
    args:
      padding_side: left
generation_args:
  max_new_tokens: 200
