# @package eval.knowundo
defaults:
  - knowundo_metrics:
    - forget_Acc
    - forget_ROUGE
    - retain_Acc
    - retain_ROUGE

handler: KnowUnDoEvaluator
output_dir: ${paths.output_dir}
metrics: {}
overwrite: false
domain: copyright
batch_size: 16
